config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  resources :users, only: :show
  get "users/:id/cars", to: "users#cars", as: :user_cars
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cars do
    resources :bookings, only: [:new, :create]
    # changed it from universal resources to only new and create as needed
    resources :reviews, only: [ :new, :create ]
  end
  resources :bookings, except: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car

  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  # price, year, model, brand, description
  # What do we need??
  validates :year, inclusion: { in: 1910..2020, message: "%{value} is not a valid year" }
  validates :year, presence: true
  validates :price, presence: true
  validates :model, presence: true
  validates :brand, presence: true
  validates :description, presence: true
  has_many_attached :photos

  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_brand,
    against: [ :brand, :model],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/map.rb
class Map < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :car

  validates :stars, inclusion: { in: 1..5, message: "Please enter a number between 1 and 5" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cars
  has_many :bookings

  has_many :incoming_bookings, through: :cars, source: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_car, except: [:destroy, :show, :edit, :update]

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
    @car = set_car
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.car = @car
    @user = current_user
    @booking.user = @user
    if @booking.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def edit
    @booking = Booking.find(params[:id])
    @car = @booking.car
  end

  def update
    @booking = Booking.find(params[:id])

    if @booking.update(booking_params)
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    car = @booking.car
    @booking.destroy
    redirect_to car_path(car)
  end

  private

  def set_car
    @car = Car.find(params[:car_id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

# Need to assign booking . user to current user for it to save

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :calculate_average_stars, only: :show

  def index
    @cars = Car.all
    if params[:query].present?
      @cars = Car.search_by_brand(params[:query])
    else
      @cars = Car.all
    end

      # adding geocoding code below
    @markers = @cars.geocoded.map do |car|
      {
        lat: car.latitude,
        lng: car.longitude,
        infoWindow: render_to_string(partial: 'info_window', locals: { car: car }),
        image_url: helpers.asset_url('miet_logo.png')
      }
    end
  end

  def show
    @car = Car.find(params[:id])
    @booking = Booking.new
    @review = Review.new

    respond_to do |format|
      format.html
      format.json { render json: { car: @car } }
    end
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user

    if @car.save
      redirect_to car_path(@car)
    else
      render :new
    end
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    if @car.update(car_params)
      redirect_to @car, notice: 'Car was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to cars_path, notice: 'Car was successfully deleted'
  end

  private

  def calculate_average_stars
    @car = Car.find(params[:id])
    sum = 0
    @car.reviews.each do |review|
      sum += review.stars
    end
    if @car.reviews.count >= 1
      @car.average_stars = sum / @car.reviews.count
    else
      @car.average_stars = nil
    end
    @car.save
  end

  def car_params
    params.require(:car).permit(:brand, :model, :year, :description, :address, :price, photos: [])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @car = Car.find(params[:car_id])
    @review.car = @car

    if @review.save
      redirect_to car_path(@car)
    else
      render :new
    end
  end


  private

  def review_params
    params.require(:review).permit(:stars)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
    @cars = @user.cars

    @your_bookings = @user.bookings

    @past_bookings = @your_bookings.where("end_date < ?", Date.today)
    @upcoming_bookings = @your_bookings.where("start_date >= ?", Date.today)

    @incoming_bookings = @user.incoming_bookings
    # @your_cars_bookings = Booking.where(cars: @cars)
  end

  def cars
    @user = current_user
    @cars = @user.cars

    @incoming_bookings = @user.incoming_bookings
    # @your_cars_bookings = Booking.where(cars: @cars)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class="container">
  <div class="small-container">
<h1>Add a booking for <%= @car.brand %> <%= @car.model %></h1>
<p><%= @car.description %></p>
<%= simple_form_for(@booking) do |f| %>
  <%= f.input :start_date, html5: true  %>
  <%= f.input :end_date, html5: true  %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>
</div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="small-container">
<h1>Add a booking for <%= @car.brand %> <%= @car.model %></h1>
<p><%= @car.description %></p>
<%= simple_form_for [@car, @booking] do |f| %>
  <%= f.input :start_date, html5: true  %>
  <%= f.input :end_date, html5: true  %>
  <%= f.button :submit, class: "btn-warning creat-booking" %>
<% end %>
</div>
</div>

app/views/bookings/show.html.erb
<h1>H1</h1>

<%= @booking.car.brand %>

app/views/cars/_info_window.html.erb
<div class="map-window">
  <% if car.photos.attached? %>
    <%= cl_image_tag car.photos[0].key %>
    <div class="map-window-infos">
      <h4><%= car.brand %> <%= car.model %></h4>
      <p><%= car.address %></p>
      <p>£<%= car.price.round %> per day</p>
      <%= link_to "More info", car_path(car), class: 'popup-button' %>
    </div>
  <% end %>
</div>

app/views/cars/edit.html.erb
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-6">
      <h1>Edit your car</h1>

      <%= simple_form_for(@car) do |f| %>
        <%= f.error_notification %>
        <%= f.input :brand %>
        <%= f.input :model %>
        <%= f.input :year %>
        <%= f.input :price, :label => "Price per day"  %>
        <%= f.input :address %>
        <%= f.input :description %>
        <%= f.submit class: 'btn-flat' %>
      <% end %>

    </div>
  </div>
</div>

app/views/cars/index.html.erb
<!-- <div class="container">
  <div class="row">
    <div class="col-sm-6 pt-8">
      <form class="form-inline">
      <div class="form-group mb-2">

     </form> -->
      <!-- <div id="Cars"> -->
        <%# @cars.each do |car| %>
          <!-- <h4><%#= car.brand  %></h4> -->
        <%# end %>
      <!-- </div> -->
      <!-- </div> -->
   <!--  </div>
  </div>
</div>
 -->


<div class="main-container justify-content-between">
  <div class="main-container-first">
    <h1>All Cars</h1>
  </div>
  <div class="main-container-second">
     <%= form_tag cars_path, method: :get, class: "d-flex" do  %>
        <%= text_field_tag :query,
           params[:query],
           class: "form-control",
           placeholder: "Find your Car..."%>
           <!-- <div class="input-group-append"> -->
            <!-- <div class="col-auto my-1"> -->
              <!-- <div class="search-button"> -->
        <%= submit_tag "Search", class: "btn-box btn-warning"  %>
           <!-- </div> -->
          <!--  </div>
           </div>
           </form>
           </div> -->
      <% end %>
  </div>


</div>
<div class="main-container">
  <div class="cards-container">
    <!-- <h1>All Cars</h1> -->
    <div class="cards">

      <% @cars.each do |car| %>
        <% if car.photos.attached? %>
          <%= link_to car_path(car), class: 'card-text' do  %>
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url('<%= cl_image_path car.photos[0].key %>')"><%= car.brand %> <%= car.model %>
            </div>
          <% end %>

        <% end %>
      <% end %>

    </div>
     </div>



    <div id="map"
      style="width: 60%; height: 100vh;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
</div>

app/views/cars/new.html.erb
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-6">
<%= simple_form_for(@car) do |f| %>
  <div class="center">
  <%= f.input :brand %>
  <%= f.input :model %>
  <%= f.input :year %>
  <%= f.input :price, :label => "Price per day"  %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.submit class: "btn btn-block btn-primary ml-8 btn-warning" %>
  <br>
  <br>


<% end %>
</div>
</div>
</div>

app/views/cars/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-sm-8">
      <div class="card-trip">
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <% @car.photos.each do |photo| %>
              <div class="carousel-item <%= " active" if photo == @car.photos.first %>">
                <%= cl_image_tag photo.key, class: "carousel-image" %>
              </div>
            <% end %>
          </div>
        </div>

        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>

        <div class="card-trip-infos">
          <div>
            <h2><%= @car.brand %> <%= @car.model %> <%= @car.year %></h2>
            <p><%= @car.description %></p>
            <p><%= @car.address %></p>
          </div>
          <h2 class="card-trip-pricing">£<%= @car.price.round %> per day</h2>
          <!-- <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" /> -->
          <div class="card-trip-user">
            <% if @car.average_stars != nil %>
              <p>
                <% @car.average_stars.times do%>
                  ⭐️
                <% end %>
              </p>
            <% end %>
          </div>
        </div>

        <% if @car.user == current_user %>
        <%= link_to "Edit car", edit_car_path(@car), class: 'btn btn-warning edit-link' %>
        <%= link_to "Delete car", car_path(@car), class: 'btn btn-warning delete-link', method: :delete, data: { confirm: "Are you sure you want to delete #{@car.model}?" } %>
        <% end %>

      </div>
    </div>

    <% if @car.user != current_user %>
      <div class="col-sm-4">

          <div class="form-container" data-controller="price">
            <h4><strong>Add a booking for <%= @car.brand %> <%= @car.model %></strong></h4>
            <p>£<%= @car.price.round %> per day</p>
            <%= simple_form_for [@car, @booking] do |f| %>
              <%= f.input :start_date, html5: true, input_html: { data: {action: "change->price#calculate", target: "price.startDate", id: @car.id} }  %>
              <%= f.input :end_date, html5: true, input_html: { data: {action: "change->price#calculate", target: "price.endDate", id: @car.id} }  %>
              <p>Estimated price:</p>
              <p>£<nobr data-target="price.datapoint">0</nobr></p>
              <%= f.button :submit, class: "btn btn-warning" %>
            <% end %>
          </div>

          <div class="form-container">
            <h4><strong>Add a review for this car</strong></h4>
            <%= simple_form_for [@car, @review] do |f| %>
              <p>Between 1 and 5</p><%= f.input :stars  %>
              <%= f.button :submit, class: "btn btn-warning" %>
            <% end %>
          </div>

      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mietyourwagon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Cabin|Roboto:400,700|Roboto+Condensed:400,700" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="page-container">
      <%= render 'shared/flashes' %>
      <div class=""><%= render 'shared/navbar' %></div>
      <div class="content-container"><%= yield %></div>
      <div class=""><%= render 'shared/footer' %></div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<section class="video">


<!--   <%= image_tag "miet_logo.png" %>
 -->
  <%= video_tag "wagon.mp4", autoplay: :autoplay, loop: :loop, muted: :muted, class: "video-background" %>

  <div class="welcome-msg">
    <h1>MIET YOUR WAGON</h1>
    <h2>Instantly <span class="coral-text">rent cars</span> near you</h2>
       <a href="/cars" class="btn btn-start">Let's go</a>
       <p class="definition">
         <strong>mieten</strong>
       </p>
        <span id="light-text">
        <em>verb

        /ˈmiːtən/</em><
        </span>
      <p class="definition">

        <strong>to rent</strong>
      </p>
  </div>
</section>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer mt-5">
    <div class="container text-left text-middle d-flex justify-content-between">
      <p><small>© 2020 Miet Your Wagon, Inc. All rights reserved</small></p>
    </div>
    <div class="footer-links" id="footer-links">
      <a href="#"><i class=""></i><small>Privacy</small></a>
      <a href="#"><i class=""></i><small>Terms</small></a>
      <a href="#"><i class=""></i><small>Sitemap</small></a>
    </div>
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
    </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/abhaila/mietyourwagon/master/app/assets/images/miet_logo.png" %>
        <span id="title">MIET YOUR WAGON</span>
    <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <% unless params[:controller] == "pages" && params[:action] == "home"  %>
          <li class="nav-item">
            <%= link_to "View all cars", cars_path, class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item active">
          <%= link_to "Hire out your car", new_car_path, class: "nav-link hire" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://avatars2.githubusercontent.com/u/68373422?s=400&u=c0305c43aae7809c60f21317727ed80471260fe0&v=4", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", edit_user_registration_path(current_user), class: "dropdown-item" %>
            <%= link_to "Manage Bookings", user_path(current_user), class: "dropdown-item", data: {turbolinks: false} %>
            <%= link_to "Manage My Wagons", user_cars_path(current_user), class: "dropdown-item", data: {turbolinks: false} %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/cars.html.erb
<div class="container mt-5">
  <h1 class="headers">Your cars</h1>
</div>
<div class="container mt-4 border-bottom border-warning border-10 d-flex justify-content-start">
  <button class="btn btn-bookings cars-tab" data-target="my-cars">Cars</button>
  <button class="btn btn-bookings cars-tab" data-target="my-cars-bookings">Car bookings</button>
</div>
<div class="container" style="margin-top: 24px;">
  <div class="bookings-ul active" id="my-cars">
    <ul class="user-bookings-ul">
      <% @cars.each do |car| %>
        <li class="user-bookings-li">
          <div class="user-bookings-box-1">
            <div class="user-bookings-box-2">
              <div class="user-bookings-box-3">
                <%= cl_image_tag car.photos[0].key, class:"user-bookings-img-box" %>
              </div>
              <div>
                <div class="user-bookings-date-box">
                <div><%= car.address %></div>
                </div>
                <div class="user-bookings-carname-box">
                  <h4><%= car.brand %> - <%= car.model %></h4>
                </div>
              </div>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="bookings-ul" id="my-cars-bookings">
    <ul class="user-bookings-ul">
      <% @incoming_bookings.each do |your_booking| %>
        <li class="user-bookings-li">
          <div class="user-bookings-box-1">
            <div class="user-bookings-box-2">
              <div class="user-bookings-box-3">
                <%= cl_image_tag your_booking.car.photos[0].key, class:"user-bookings-img-box" %>
              </div>
              <div>
                <div class="user-bookings-date-box">
                <div><%= your_booking.start_date.strftime("%b %d, %Y") %> - <%= your_booking.end_date.strftime("%b %d, %Y") %></div>
                </div>
                <div class="user-bookings-carname-box">
                  <h4><%= your_booking.car.brand %> - <%= your_booking.car.model %></h4>
                </div>
              </div>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-5">
  <h1 class="headers">Trips</h1>
</div>
<div class="container mt-4 border-bottom border-warning border-10 d-flex justify-content-start">
  <button class="btn btn-bookings booking-tab" data-target="upcoming-bookings">Upcoming</button>
  <button class="btn btn-bookings booking-tab" data-target="past-bookings">Past</button>
</div>
<div class="container" style="margin-top: 24px;">
  <div class="bookings-ul active" id="upcoming-bookings">
    <ul class="user-bookings-ul">
      <% @upcoming_bookings.each do |your_booking| %>
        <li class="user-bookings-li">
          <div class="user-bookings-box-1">
            <div class="user-bookings-box-2">
              <div class="user-bookings-box-3">
                <%= cl_image_tag your_booking.car.photos[0].key, class:"user-bookings-img-box" %>
              </div>
              <div>
                <div class="user-bookings-date-box">
                <div><%= your_booking.start_date.strftime("%b %d, %Y") %> - <%= your_booking.end_date.strftime("%b %d, %Y") %></div>
                </div>
                <div class="user-bookings-carname-box">
                  <h4><%= your_booking.car.brand %> - <%= your_booking.car.model %></h4>
                  <!-- <h6  class="edit-buttton">Edit</h6>
                  <h6 class="edit-buttton">Delete</h6> -->
                </div>
              </div>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="bookings-ul" id="past-bookings">
    <ul class="user-bookings-ul">
      <% @past_bookings.each do |your_booking| %>
        <li class="user-bookings-li">
          <div class="user-bookings-box-1">
            <div class="user-bookings-box-2">
              <div class="user-bookings-box-3">
                <%= cl_image_tag your_booking.car.photos[0].key, class:"user-bookings-img-box" %>
              </div>
              <div>
                <div class="user-bookings-date-box">
                <div><%= your_booking.start_date.strftime("%b %d, %Y") %> - <%= your_booking.end_date.strftime("%b %d, %Y") %></div>
                </div>
                <div class="user-bookings-carname-box">
                  <h4><%= your_booking.car.brand %> - <%= your_booking.car.model %></h4>
                </div>
              </div>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>